In [1]:
print("Hello World!")


Hello World!


In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr1=np.array([[1,2,3],[4, 5, 6],[7,8,9]])
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)

<class 'numpy.ndarray'>
2
(3, 3)
9


ARRAY CREATION!!!!

In [4]:
#using list
a=np.array([[1,2,3],[4, 5, 6]],dtype=float)
print("A :", a)
#using tuple
b=np.array((1,2,3))
print("B :", b)    
#c=np.zeroes((2,5))
#filling 1
c=np.ones((2,5))
print("C :", c) 
#filling array with constant complex number
d=np.full((3,3),6,dtype='complex')
print("D :",d)
e=np.eye(3)
print("E :",e)

A : [[1. 2. 3.]
 [4. 5. 6.]]
B : [1 2 3]
C : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
D : [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
E : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


ARRAY RESIZING!!!!

In [6]:
#np.arrange(0,20,3) --> 0,3,6,9,12,15,18
#np.arrange(0,30,3) --> 0,3,6,9,12,15,18,21,24,27,30
np.linspace(0,5,10) # linspace --> equally spaced 10 elements
arr2=np.array([[1,2,3],[4,5,6]])
arr2=arr2.reshape(3,2)
print(arr2)
arr2=arr2.flatten()
print(arr2)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


SLICING AND INDEXING!!!!

In [7]:
#indexing and slicing
arr3=np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15],
               [16,17,18,19,20]])
print(arr3[1:3,2:4])
print(arr3[::2,::])
print(arr3[1::2,1::3])

[[ 8  9]
 [13 14]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[ 7 10]
 [17 20]]


In [8]:
#broadcasting in numpy
arr4=np.array([[1,2,3,4,5],
        [6,7,8,9,10]])
print(arr4*3)
print(arr4+1)
print(arr4.T)

[[ 3  6  9 12 15]
 [18 21 24 27 30]]
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


BASIC FUNCTIONS!!!!

In [9]:
arr5=np.array([[1,2,3],
               [4,5,6],
                [7,8,9],
              [10,11,12]])
print(arr5.max())
print(arr5.max(axis=0))
print(arr5.max(axis=1))
print(arr5.min())
print(arr5.min(axis=0))
print(arr5.min(axis=1))
print(arr5.sum())
print(arr5.cumsum(axis=0))
print(arr5.cumsum(axis=1))

12
[10 11 12]
[ 3  6  9 12]
1
[1 2 3]
[ 1  4  7 10]
78
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]
 [22 26 30]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]
 [10 21 33]]


SORTING !!!!

In [10]:
arr6=np.array([[3,6,2,4],
               [8,5,3,6]])
np.sort(arr6,axis=1) #sorting row wise
print(arr6)
arr6=np.array([[3,6,2,4],
               [8,5,3,6]])
np.sort(arr6,axis=0,kind='mergesort')
print(arr6)
dtypes=[('name','S10'),('grad_yr',int),('cgpa',float)]
values=[('HRITIK',2009,7.9),('DANNY',2008,8.6),('Sachin',2009,6.8),('Harry',2007,9.9)]
arr7=np.array(values,dtype=dtypes)
print(np.sort(arr7,order='name'))
print(np.sort(arr7,order=['grad_yr','name']))

[[3 6 2 4]
 [8 5 3 6]]
[[3 6 2 4]
 [8 5 3 6]]
[(b'DANNY', 2008, 8.6) (b'HRITIK', 2009, 7.9) (b'Harry', 2007, 9.9)
 (b'Sachin', 2009, 6.8)]
[(b'Harry', 2007, 9.9) (b'DANNY', 2008, 8.6) (b'HRITIK', 2009, 7.9)
 (b'Sachin', 2009, 6.8)]


STACKING AND SPLITTING!!!

In [15]:
A1=np.array([[1,2],[3,4]])
A2=np.array([[5,6],[7,8]])
A3=np.array([8,9])
print(np.vstack((A1,A2)))
print(np.hstack((A1,A2)))
print(np.column_stack((A1,A3)))
print(np.concatenate((A1,A2),0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 8]
 [3 4 9]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


MATHS FUNCTIONS!!!!

In [21]:
arr8=np.array([1,2,6,9,3,6])
wt=np.array([10,15,20,25,30,35])
np.min(arr8)
np.max(arr8)
print(np.mean(arr8))   #mean
print(np.median(arr8)) #median
print(np.average(arr8,weights=wt)) #weighted average
#standard deviation
u=np.mean(arr8)
mystd=np.sqrt(np.mean(abs(arr8-u)**2))
dev=np.std(arr8)
print(mystd,dev)
#variance
print(mystd**2,np.var(arr8))

4.5
4.5
5.074074074074074
2.753785273643051 2.753785273643051
7.583333333333333 7.583333333333333


RANDOM FUNCTIONS!!!!

In [26]:
arr9=np.array([1,2,3,4,5,6,7,8,9])
#x=np.arrange(10)+5
x=np.random.seed(1)
print(x)
print(np.random.shuffle(arr9))

None
None


In [27]:
a=np.random.randn(2,3)
print(a)
a=np.random.randint(5,10,3)
print(a)
a=np.random.choice([2,4,6,8,98,45])
print(a)

[[-0.54974618 -1.40287272  1.5827523 ]
 [-1.04514683  0.25759352 -1.9593946 ]]
[9 7 9]
45
